apiVersion: apps/v1
kind: Deployment
metadata:
  name: meows-controller
  namespace: meows
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: controller
        image: meows-controller:kindtest
        imagePullPolicy: Never
        args:
        - "--runner-manager-interval=10s"
