name: job-success-org-runner
on: push

jobs:
  build:
    name: job-success-org-runner
    runs-on: [self-hosted, "{{.Namespace}}/{{.RunnerPool}}"]
    steps:
      - run: job-started
      - run: job-success
