name: Remove test branches and runners
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 15 * * *'

jobs:
  remove-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure GIT
        run: |
          git config user.name "Daily CI"
          git config user.email "example@example.com"
      - name: Remove test branches
        run: |
          git fetch origin
          for branch in $(git branch -r | sed -e 's|^[[:blank:]]*origin/||' | grep "^test-branch-"); do
            git push --delete origin $branch
          done

  remove-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: cybozu-go/meows
          path: meows
      - uses: actions/setup-go@v4
        with:
          go-version-file: meows/go.mod
      - name: Remove offline runners
        working-directory: meows
        run: |
          echo '${{ secrets.APP_PRIVATE_KEY }}' > /tmp/private-key.pem
          go install ./cmd/meows
          list=(${GITHUB_REPOSITORY/\// })
          org=${list[0]}
          repo=${list[1]}
          meows runner remove $org       --app-id ${{ secrets.APP_ID }} --app-installation-id ${{ secrets.APP_INSTALLATION_ID }} --app-private-key-path /tmp/private-key.pem
          meows runner remove $org/$repo --app-id ${{ secrets.APP_ID }} --app-installation-id ${{ secrets.APP_INSTALLATION_ID }} --app-private-key-path /tmp/private-key.pem
