name: slack-channel-specified
on: push

jobs:
  build:
    name: job-success
    runs-on: [self-hosted, "{{.Namespace}}/{{.RunnerPool}}"]
    # It expects a notification to be sent to "#test1".
    env:
      MEOWS_SLACK_CHANNEL: "#test2"
    steps:
      - run: job-started
      - run: echo "#test1" > /var/meows/slack_channel
      - run: job-success
