apiVersion: meows.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: org-runnerpool1
spec:
  replicas: 1
  maxRunnerPods: 1
  slackAgent:
    serviceName: slack-agent.meows.svc
    channel: "#test1"
  template:
    image: meows-runner:kindtest
    imagePullPolicy: Never
    env:
    - name: EXTEND_DURATION
      value: "30s"
