apiVersion: meows.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: org-runnerpool1
spec:
  replicas: 1
  organization: neco-test
  credentialSecretName: github-cred-foo
  maxRunnerPods: 1
  notification:
    slack:
      enable: true
      channel: "#test1"
    extendDuration: "30s"
  template:
    runnerContainer:
      image: meows-runner:kindtest
      imagePullPolicy: Never
