apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-agent
  namespace: meows
spec:
  template:
    spec:
      containers:
      - name: agent
        image: meows-controller:kindtest
        imagePullPolicy: Never
