apiVersion: meows.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: repo-runnerpool2
spec:
  repository: neco-test/meows-ci
  setupCommand:
  - "bash"
  - "-c"
  - "date > /tmp/test"
  slackNotification:
    enable: true
    channel: "#test2"
    extendDuration: "30s"
  template:
    image: meows-runner:kindtest
    imagePullPolicy: Never
