apiVersion: actions.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: runnerpool-sample
spec:
  repositoryName: repository-sample
  slackAgentServiceName: slack-agent
  replicas: 3
  template:
    image: actions-runner:latest
