namespace: meows

images:
- name: quay.io/cybozu/meows-controller
  newTag: 0.12.0

commonLabels:
  app.kubernetes.io/name: meows
  app.kubernetes.io/component: slack-agent

resources:
- manifests.yaml
