apiVersion: meows.cybozu.com/v1alpha1
kind: RunnerPool
metadata:
  name: repo-runnerpool1
spec:
  repository: neco-test/meows-ci
  replicas: 3
  notification:
    slack:
      enable: true
      channel: "#test1"
    extendDuration: "30s"
  template:
    runnerContainer:
      image: meows-runner:kindtest
      imagePullPolicy: Never
