name: main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make setup
      - run: make lint
      - run: make check-generate
      - run: make test
      - run: make build
      - run: make image
  kindtest:
    name: Run test on kind
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Create secret files
        run: |
          echo '${{ secrets.APP_PRIVATE_KEY }}' > .secret.private-key.pem
          echo 'export GITHUB_APP_ID=${{ secrets.APP_ID }}'                           > .secret.env.sh
          echo 'export GITHUB_APP_INSTALLATION_ID=${{ secrets.APP_INSTALLATION_ID }}' >> .secret.env.sh
          echo 'export SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}'                    >> .secret.env.sh
          echo 'export SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }}'                >> .secret.env.sh
          echo 'export SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}'                >> .secret.env.sh
      - run: make setup
      - run: make -C kindtest start
      - run: make -C kindtest test
      - run: make -C kindtest logs
        if: always()
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs.tar.gz
          path: kindtest/logs.tar.gz
