name: main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make setup
      - run: make lint
      - run: make check-generate
      - run: make test
      - run: make build
      - run: make image
  kindtest:
    name: Run test on kind
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Configure GIT
        run: |
          git config --global user.email "example@example.com"
          git config --global user.name "ci-kindtest"
          echo '${{ secrets.TESTREPO_DEPLOY_KEY }}' > /tmp/deploy-key.pem
          chmod 600 /tmp/deploy-key.pem
      - name: Create secret files
        run: |
          echo '${{ secrets.APP_PRIVATE_KEY }}' > .secret.private-key.pem
          cat <<'EOF' > .secret.env.sh
          export GITHUB_APP_ID=${{ secrets.APP_ID }}
          export GITHUB_APP_INSTALLATION_ID=${{ secrets.APP_INSTALLATION_ID }}
          export SLACK_CHANNEL=${{ secrets.SLACK_CHANNEL }}
          export SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }}
          export SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}
          EOF
      - run: make setup
      - run: make -C kindtest start
      - run: make -C kindtest test
        env:
          GIT_SSH_COMMAND: "ssh -i /tmp/deploy-key.pem"
      - run: make -C kindtest logs
        if: always()
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs.tar.gz
          path: kindtest/logs.tar.gz
